### ISSUE TITLE
Assertion Failed Exception !

### ISSUE THREAD

**Issue by HanyHossny** [rvitorgomes/signature-opencv#1]
I tried to run this code multiple times, but I always get the exception below and none of the fixes mentioned online worked with it. Would you take a look into it and tell how to fix this ??

===================================
%run ./index.py --dataset "./dataset" --save "./results"
Start Processing
Traceback (most recent call last):

  File "D:\ThisPC\Documents\Python Scripts\Signature Checker\signature_extractor_4\index.py", line 114, in <module>
    main(sys.argv)

  File "D:\ThisPC\Documents\Python Scripts\Signature Checker\signature_extractor_4\index.py", line 111, in main
    process_images(DATASET)

  File "D:\ThisPC\Documents\Python Scripts\Signature Checker\signature_extractor_4\index.py", line 97, in process_images
    contours = find_contours(image)

  File "D:\ThisPC\Documents\Python Scripts\Signature Checker\signature_extractor_4\index.py", line 54, in find_contours
    blur = cv2.GaussianBlur(image,(11,11),0)

error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\core\src\matrix.cpp:757: error: (-215:Assertion failed) dims <= 2 && step[0] > 0 in function 'cv::Mat::locateROI'
=========================

**Comment by malingamesfr** [comment]
Hello you have to add * .extension in the dataset
 
"%run ./index.py -- dataset "./dataset/***.jpg**" --save "./results"
